"""Criacao das tabelas iniciais

Revision ID: 9f7358ca7c3f
Revises: 
Create Date: 2026-03-28 12:17:38.187965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7358ca7c3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('sessoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_data', sa.DateTime(), nullable=False),
    sa.Column('is_dub', sa.Boolean(), nullable=False),
    sa.Column('sala', sa.String(length=20), nullable=False),
    sa.Column('filme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('sessao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sessao_id', sa.Integer(), nullable=False),
    sa.Column('assento_id', sa.Integer(), nullable=False),
    sa.Column('data_reserva', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assento_id'], ['assentos.id'], ),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('assentos')
    op.drop_table('sessoes')
    op.drop_table('users')
    op.drop_table('filmes')
    # ### end Alembic commands ###
